// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuXWtYbhv69KUPb0txw1wcVrAq3Gi_5wg',
    appId: '1:931235749581:web:a673704d04ff0784819384',
    messagingSenderId: '931235749581',
    projectId: 'isms-2c025',
    authDomain: 'isms-2c025.firebaseapp.com',
    storageBucket: 'isms-2c025.appspot.com',
    measurementId: 'G-4XCDLFSNCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFNusytMFdzyjx40OZwAYH0iTF6HWKPw',
    appId: '1:931235749581:android:dda2cf99012f1d13819384',
    messagingSenderId: '931235749581',
    projectId: 'isms-2c025',
    storageBucket: 'isms-2c025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0Dq-B9J_6K2tXhCF0CB3G_B--t2Irkk',
    appId: '1:931235749581:ios:1a48578ba8fa121b819384',
    messagingSenderId: '931235749581',
    projectId: 'isms-2c025',
    storageBucket: 'isms-2c025.appspot.com',
    androidClientId: '931235749581-0ossdpsusvkjakudi84ragh94p2td7vt.apps.googleusercontent.com',
    iosClientId: '931235749581-bnrf5esofvd3m6f8hi7hsq2sb2ltk5kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.isms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0Dq-B9J_6K2tXhCF0CB3G_B--t2Irkk',
    appId: '1:931235749581:ios:d429fd9f34c7aabc819384',
    messagingSenderId: '931235749581',
    projectId: 'isms-2c025',
    storageBucket: 'isms-2c025.appspot.com',
    androidClientId: '931235749581-0ossdpsusvkjakudi84ragh94p2td7vt.apps.googleusercontent.com',
    iosClientId: '931235749581-kdkloent0cqvlvikbot8na16e1db2ec1.apps.googleusercontent.com',
    iosBundleId: 'com.example.isms.RunnerTests',
  );
}
